- name: Check if selinux is installed
  command: getenforce
  register: command_result
  changed_when: False
  ignore_errors: True

- name: Install libselinux-python
  yum: name={{ item }}
  with_items: 
    - epel-release
    - libselinux-python
  when: command_result|success and command_result.stdout != 'Disabled'

- copy: src=mariadb.repo dest=/etc/yum.repos.d/mariadb.repo

- yum: name={{ item }} state=installed
  with_items:
  - MariaDB
  - MariaDB-devel
  - MySQL-python
  environment:
    http_proxy: "{{http_proxy}}"

- service: name=mysql state=started

- name: Create Database
  mysql_db: name=alminium encoding=utf8 state=present

- name: Create User on MySQL/MariaDB
  mysql_user: name=alminium password="{{dbpasswd}}" priv=alminium.*:ALL state=present


